### ISSUE TITLE
Cannot get model_type from the deploy service

### ISSUE THREAD

**Issue by Harry-zzh** [modelscope/ms-swift#1904]
Thank you for your exceptional work! I'm a beginner with this repository. I encountered an error when running `swift eval --model_type llava1_5-7b-instruct --eval_dataset okvqa` on my CPU. The error message reads, "Cannot get model_type from the deploy service, please check the error to continue eval." I'm unsure why this is happening and I would appreciate any assistance you could provide. Thank you in advance!

**Comment by tastelikefeet** [comment]
Cannot reproduce your problem, however, I met the following issue:
`INFO: 2024-09-05 14:00:56,278 deploy.py:56] {'num_prompt_tokens': 0, 'num_generated_tokens':`
This is because you are using an unsupported eval dataset.
My suggestion is to use the latest main branch of swift and the latest version of transformers.
To check the eval functionality, please view:
https://swift.readthedocs.io/en/latest/Instruction/LLM-eval.html

**Comment by Harry-zzh** [comment]
Thank you. When I manually set the --model_id_or_path, the issue of "Cannot get model_type from the deploy service" is resolved.

Next, I try to use a supported evaluation dataset called "POPE". However, I am unsure how to manually download it and which directory to place it in. This is because my GPU machine cannot connect to the website, so I need to download the dataset manually.
